BTN_START_CRAWLING_X_START = 10
BTN_START_CRAWLING_Y_START = 70
BTN_START_CRAWLING_WIDTH = 300
BTN_START_CRAWLING_HEIGHT = 250
BTN_START_CRAWLING_X_END = BTN_START_CRAWLING_X_START + BTN_START_CRAWLING_WIDTH
BTN_START_CRAWLING_Y_END = BTN_START_CRAWLING_Y_START + BTN_START_CRAWLING_HEIGHT
