BTN_START_CRAWLING_X_START = 10
BTN_START_CRAWLING_Y_START = 70
BTN_START_CRAWLING_WIDTH = 300
BTN_START_CRAWLING_HEIGHT = 250
BTN_START_CRAWLING_X_END = BTN_START_CRAWLING_X_START + BTN_START_CRAWLING_WIDTH
BTN_START_CRAWLING_Y_END = BTN_START_CRAWLING_Y_START + BTN_START_CRAWLING_HEIGHT

EDT_START_DATE_X_START = BTN_START_CRAWLING_X_END + 10
EDT_START_DATE_Y_START = BTN_START_CRAWLING_Y_START + 10
EDT_START_DATE_WIDTH = 100
EDT_START_DATE_HEIGHT = 30
EDT_START_DATE_X_END = EDT_START_DATE_X_START + EDT_START_DATE_WIDTH
EDT_START_DATE_Y_END = EDT_START_DATE_Y_START + EDT_START_DATE_HEIGHT

EDT_END_DATE_X_START = BTN_START_CRAWLING_X_END + 10
EDT_END_DATE_Y_START = EDT_START_DATE_Y_END + 10
EDT_END_DATE_WIDTH = 100
EDT_END_DATE_HEIGHT = 30
EDT_END_DATE_X_END = EDT_END_DATE_X_START + EDT_END_DATE_WIDTH
EDT_END_DATE_Y_END = EDT_END_DATE_Y_START + EDT_END_DATE_HEIGHT

EDT_KEYWORD_X_START = BTN_START_CRAWLING_X_END + 10
EDT_KEYWORD_Y_START = EDT_END_DATE_Y_END + 10
EDT_KEYWORD_WIDTH = 100
EDT_KEYWORD_HEIGHT = 30
EDT_KEYWORD_X_END = EDT_KEYWORD_X_START + EDT_KEYWORD_WIDTH
EDT_KEYWORD_Y_END = EDT_KEYWORD_Y_START + EDT_KEYWORD_HEIGHT


